"""booking_status

Revision ID: e51f0633439b
Revises: 3d85b94df5b8
Create Date: 2025-12-14 16:25:30.121461

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e51f0633439b"
down_revision: Union[str, Sequence[str], None] = "3d85b94df5b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "booking",
        sa.Column("status", sa.String(), nullable=False, server_default="pending"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("booking", "status")
    # ### end Alembic commands ###
