"""client name not unique

Revision ID: 3d85b94df5b8
Revises: 0a10e771a88a
Create Date: 2025-12-08 10:56:27.835482

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "3d85b94df5b8"
down_revision: Union[str, Sequence[str], None] = "0a10e771a88a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
