"""field work_schedule for company

Revision ID: 5f8b401e2873
Revises: 768de22428b8
Create Date: 2025-11-29 09:00:12.466735

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5f8b401e2873"
down_revision: Union[str, Sequence[str], None] = "768de22428b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "company",
        sa.Column(
            "work_schedule", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("company", "work_schedule")
    # ### end Alembic commands ###
