"""field_booking_url_company_model

Revision ID: 6c83152d5ae1
Revises: 5f8b401e2873
Create Date: 2025-11-29 21:04:10.170386

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6c83152d5ae1"
down_revision: Union[str, Sequence[str], None] = "5f8b401e2873"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "company", sa.Column("booking_url", sa.String(length=255), nullable=True)
    )
    op.create_unique_constraint(
        op.f("uq_company_booking_url"), "company", ["booking_url"]
    )
    op.alter_column("company", "hash_password", new_column_name="password")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "company",
        sa.Column("hash_password", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(op.f("uq_company_password"), "company", type_="unique")
    op.drop_constraint(op.f("uq_company_booking_url"), "company", type_="unique")
    op.create_unique_constraint(
        op.f("uq_company_hash_password"),
        "company",
        ["hash_password"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("company", "booking_url")
    op.drop_column("company", "password")
    # ### end Alembic commands ###
