"""back_populates Booking

Revision ID: 0a10e771a88a
Revises: 9b04699e3004
Create Date: 2025-12-07 18:36:53.798349

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "0a10e771a88a"
down_revision: Union[str, Sequence[str], None] = "9b04699e3004"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
