"""remove_client_id_service_model

Revision ID: 33add2df6ad7
Revises: db38ab285980
Create Date: 2025-11-30 01:54:21.070735

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "33add2df6ad7"
down_revision: Union[str, Sequence[str], None] = "db38ab285980"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_service_client_id_client"), "service", type_="foreignkey"
    )
    op.drop_column("service", "client_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service",
        sa.Column("client_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_service_client_id_client"), "service", "client", ["client_id"], ["id"]
    )
    # ### end Alembic commands ###
